{
 "title": "Vessim Dashboard",
 "time": { "from": "2022-06-15T00:00:00.000Z", "to": "2022-07-04T23:55:00.000Z" },
 "panels": [
  {
   "title": "Solar Leistung",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "select power_solar,time from vessim "
    }
   ]
  },
  {
   "title": "Solar erzeugung pro Tag",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  DATE_TRUNC('day', time) AS time,\r\n  AVG(power_solar)*24/1000 AS avg_power_solar\r\nFROM \"vessim\"\r\nWHERE $__timeFilter(time)\r\nGROUP BY 1\r\nORDER BY 1;\r\n"
    }
   ]
  },
  {
   "title": "Erzeugung-Verbrauch ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  DATE_TRUNC('day', time) AS time,\r\n  AVG(power_solar)*24/1000 + AVG(power_server)*24/1000 AS avg_power_solar\r\n  \r\nFROM \"vessim\"\r\nWHERE $__timeFilter(time)\r\nGROUP BY 1\r\nORDER BY 1;\r\n"
    }
   ]
  },
  {
   "title": "Ladestand Batterie",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "dataset": "iox", "rawSql": "select time,soc FROM vessim" }
   ]
  }
 ]
}