{
 "title": "Vessim Dashboard",
 "time": { "from": "2022-06-15T00:00:00.000Z", "to": "2022-07-04T23:55:00.000Z" },
 "panels": [
  {
   "title": "Solar Leistung",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"vessim_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"vessim\" and\n    r._field == \"power_solar\"\n  )"
    }
   ]
  },
  {
   "title": "Solar erzeugung pro Tag",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"vessim_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"vessim\" and\n    r._field == \"power_solar\"\n  )\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with _value: r._value * 24.0 / 1000.0 }))\n  |> rename(columns: {_value: \"avg_power_solar\"})"
    }
   ]
  },
  {
   "title": "Erzeugung-Verbrauch ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "data =\n  from(bucket: \"vessim_bucket\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) =>\n      r._measurement == \"vessim\" and\n      (r._field == \"power_solar\" or r._field == \"power_server\")\n    )\n    |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)\n    |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n    |> map(fn: (r) => ({\n        r with\n        _value: (r.power_solar + r.power_server) * 24.0 / 1000.0\n    }))\n\ndata\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_value: \"avg_power_solar\"})"
    }
   ]
  },
  {
   "title": "Ladestand Batterie",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"vessim_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"vessim\" and\n    r._field == \"soc\"\n  )"
    }
   ]
  }
 ]
}